# Generated by Django 3.2 on 2021-05-03 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FinologProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jira_key', models.CharField(max_length=50)),
                ('finolog_id', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'проект в Финологе',
                'verbose_name_plural': 'проекты в Финологе',
            },
        ),
        migrations.AlterModelOptions(
            name='finologorder',
            options={'verbose_name': 'заказ в Финологе', 'verbose_name_plural': 'заказы в Финологе'},
        ),
        migrations.AlterModelOptions(
            name='issuesinfo',
            options={'verbose_name': 'таск', 'verbose_name_plural': 'таски'},
        ),
    ]
