# Generated by Django 3.2 on 2022-02-17 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0002_auto_20210503_1139'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProxyModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Njndesm',
            },
        ),
    ]
