# Generated by Django 3.2 on 2022-03-08 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0006_alter_finologproject_finolog_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='PeriodForDownloadModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('days', models.IntegerField(blank=True, null=True)),
                ('start_date', models.DateField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': '!  Период, за который необходимо загрузить ворклоги',
            },
        ),
        migrations.DeleteModel(
            name='DaysForDownloadModel',
        ),
    ]
