# Generated by Django 3.2 on 2022-03-08 08:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0007_auto_20220308_0819'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='periodfordownloadmodel',
            options={'verbose_name_plural': '! Период, за который необходимо загрузить ворклоги'},
        ),
    ]
