# Generated by Django 3.2 on 2022-03-31 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0012_alter_finologproject_category_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='finologproject',
            name='category_id',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
