version: '2.4'
services:

  api:
    volumes:
      - ./api:/usr/src/api
      - /usr/src/webroot
    environment:
      DEBUG: 'yes'
    environment:
      SERVER_NAME: ${SERVER_NAME}
    command: >
      uwsgi
        --socket 0.0.0.0:8000
        --master
        --processes 1
        --threads 4
        --python-autoreload 1
        --wsgi-file ./jira/wsgi.py

# Use --socket 0.0.0.0:8000 for working with nginx
# Use --http 0.0.0.0:8000 for working with nginx

  nginx:
    ports:
      - "80:80"
